require('dotenv').config({ path: 'envs/.env.development' });

import express from 'express';

const app = express();

const { APP_PROTOCOL, APP_HOST, APP_MOCK_PORT } = process.env;

app.all('/*', (req,res,next) => {
  res.header('access-token' , 'dqleub-mNG3aScinWC8J_g');
  res.header('client', 'dqleub-mNG3aScinWC8J_g');
  res.header('uid', 'user@user.com');
  next();
});

app.get('/api/users/fund_actions', (req, res, next) => {
  res.json({
    "limit":10,
    "page":0,
    "page_count":3,
    "fund_actions":[
      {
        "id":4324,
        "amount":"3.0",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-02-03T06:26:19.518-05:00",
        "updated_at":"2017-02-03T06:26:21.300-05:00",
        "account_id":"1639",
        "status":"not_enough_money",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"deposit",
        "error_text":null,
        "closed_on_dashboard":false,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":null,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4321,
        "amount":"2.0",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-02-02T13:21:56.953-05:00",
        "updated_at":"2017-02-02T13:22:01.417-05:00",
        "account_id":"1639",
        "status":"pending_on_vanare",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"withdraw",
        "error_text":null,
        "closed_on_dashboard":false,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":null,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4317,
        "amount":"2.0",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-02-02T13:17:48.045-05:00",
        "updated_at":"2017-02-02T13:17:52.770-05:00",
        "account_id":"1639",
        "status":"pending_on_vanare",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"withdraw",
        "error_text":null,
        "closed_on_dashboard":false,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":null,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4314,
        "amount":"2.0",
        "user_id":257,
        "bank_instruction_id":null,
        "created_at":"2017-02-02T13:02:22.112-05:00",
        "updated_at":"2017-02-02T13:02:28.134-05:00",
        "account_id":"1638",
        "status":"pending_on_vanare",
        "bank_name":null,
        "client_bank_account_number":null,
        "type":"internal",
        "error_text":null,
        "closed_on_dashboard":false,
        "account_number":"901132360",
        "ira_fund_date":null,
        "receiving_account_number":"901336860",
        "complete_by_td_at":null,
        "vanare_transaction_id":"124843",
        "recurring_transaction_group_id":null,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4309,
        "amount":"2.0",
        "user_id":257,
        "bank_instruction_id":null,
        "created_at":"2017-02-01T15:03:25.856-05:00",
        "updated_at":"2017-02-01T15:03:28.823-05:00",
        "account_id":"1639",
        "status":"pending_on_vanare",
        "bank_name":null,
        "client_bank_account_number":null,
        "type":"internal",
        "error_text":null,
        "closed_on_dashboard":false,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":"901132360",
        "complete_by_td_at":null,
        "vanare_transaction_id":"124841",
        "recurring_transaction_group_id":null,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4285,
        "amount":"25.25",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-01-30T11:00:20.612-05:00",
        "updated_at":"2017-01-30T11:00:31.604-05:00",
        "account_id":"1639",
        "status":"not_enough_money",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"deposit",
        "error_text":null,
        "closed_on_dashboard":true,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":153,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4248,
        "amount":"25.25",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-01-23T11:00:19.841-05:00",
        "updated_at":"2017-01-23T11:00:48.977-05:00",
        "account_id":"1639",
        "status":"not_enough_money",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"deposit",
        "error_text":null,
        "closed_on_dashboard":true,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":153,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4209,
        "amount":"25.25",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-01-16T11:00:20.165-05:00",
        "updated_at":"2017-01-16T11:00:51.879-05:00",
        "account_id":"1639",
        "status":"not_enough_money",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"deposit",
        "error_text":null,
        "closed_on_dashboard":true,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":153,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":4171,
        "amount":"25.25",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-01-09T11:00:19.703-05:00",
        "updated_at":"2017-01-09T11:01:28.526-05:00",
        "account_id":"1639",
        "status":"not_enough_money",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"deposit",
        "error_text":null,
        "closed_on_dashboard":true,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":null,
        "recurring_transaction_group_id":153,
        "completion_method":null,
        "initial_deposit":false
      },
      {
        "id":3991,
        "amount":"25.25",
        "user_id":257,
        "bank_instruction_id":"3799266",
        "created_at":"2017-01-02T11:00:23.771-05:00",
        "updated_at":"2017-05-12T08:00:15.449-04:00",
        "account_id":"1639",
        "status":"pending_on_vanare",
        "bank_name":"WELLS FARGO BANK",
        "client_bank_account_number":"********8671",
        "type":"deposit",
        "error_text":null,
        "closed_on_dashboard":true,
        "account_number":"901336860",
        "ira_fund_date":null,
        "receiving_account_number":null,
        "complete_by_td_at":null,
        "vanare_transaction_id":"58",
        "recurring_transaction_group_id":153,
        "completion_method":null,
        "initial_deposit":false
      }
    ]
  });
});

app.listen(APP_MOCK_PORT, () => {
  console.log(`Mock server listening at: ${APP_PROTOCOL}://${APP_HOST}:${APP_MOCK_PORT}`);
});